### ISSUE TITLE
Hard refresh on Next.JS refactor breaks CSS

### ISSUE THREAD

**Issue by theavgeekbee** [trinityacademics/trinityacademics#1]
Refreshing the main page when running `reactjs-refactor` on Next JS breaks the CSS.

Steps to Reproduce:
1. Launch NextJS
2. Go to main page. ![before](https://cdn.discordapp.com/attachments/1208509232715010190/1209217095343280158/image.png?ex=65e61e2d&is=65d3a92d&hm=04d02026db017b10ee54ecac5ebdeffda89c86dedb33f148907966c2c83a0f3b&)
4. Go to science page
5. Click the top link to go back to the home page
6. Refresh using the Ctrl+R or browser refresh button
7. ![after](https://cdn.discordapp.com/attachments/1208509232715010190/1209217556334911488/image.png?ex=65e61e9b&is=65d3a99b&hm=2b411e6afaf00a81e1d4daad4d97ad77f964d413813bff21f93cdaf8835c000b&)

**Comment by ASZM101** [comment]
I'm working on it!

**Comment by theavgeekbee** [comment]
moved science folder and math folder to separate directory (problem fixed for now)

**Comment by theavgeekbee** [comment]
Fixed in 17ee9b5
